  nginx:
      image: nginx
      restart: always
      expose:
         - "80"
      ports:
          - "80:8090"
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
          - /app/zn/deploy/dist:/usr/share/nginx/html
  simulatorsrv:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /simulatorsrv
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /app/zn/deploy/simulator_restfulapi:/simulatorsrv
      - /app/zn/deploy/dist/log:/dist/log
    environment:
      - listenport=8080
    ports:
       - "8080:8080"
    expose:
       - "8080"
  znserver:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /app/zn/deploy/srv:/app
      - /app/zn/deploy/dist/log:/dist/log
    environment:
      - srvredis_host=172.17.42.1
      - MONGO_URL=mongodb://172.17.42.1/zhongnandb
      - listenport=3005
    external_links:
      - mongodb
      - redis
    ports:
       - "3005:3005"
    expose:
       - "3005"
  uploadsrv:
    image: node:6.11.2
    restart: always
    command: node ./index.js
    working_dir: /app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /app/zn/deploy/uploadsrv:/app
      - /app/zn/deploy/dist/log:/dist/log
      - /app/zn/deploy/dist/uploader:/dist/uploaddir
    environment:
      - srvredis_host=172.17.42.1
      - uploaddir=/dist/uploaddir
      - logdir=/dist/log
      - platformserverurl=http://172.17.42.1:8080
    external_links:
      - mongodb
      - redis
