redis:
  image:  redis:4.0.8
  container_name: redis
  restart: always
  expose:
     - "6379"
  volumes:
     - /etc/localtime:/etc/localtime:ro
     - /500g/redis:/var/lib/redis
  ports:
     - "6379:6379"
